# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20171007_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='producinorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
